# Dependencies
markdown:         redcarpet
highlight:        true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
sass:
  sass_dir:       public/css
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Defaults
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
